set(CMAKE_SYSTEM_NAME "Generic")
set(CMAKE_C_COMPILER avr-gcc)
set(CMAKE_CXX_COMPILER avr-g++)
include_directories("$ENV{ARDUINOCORE}/cores/arduino")
include_directories("$ENV{ARDUINOCORE}/variants/standard")
set(CMAKE_CXX_FLAGS "-MMD -mmcu=atmega328p -Wall -DF_CPU=16000000L -Os")
set(CMAKE_C_FLAGS "-MMD -mmcu=atmega328p -Wall -DF_CPU=16000000L -Os")
